### ISSUE TITLE
Foreign.Object instead of Foreign?

### ISSUE THREAD

**Issue by jamesdbrock** [purescript-web/purescript-web-html#51]
Should this use [`Foreign.Object`](https://pursuit.purescript.org/packages/purescript-foreign-object/2.0.3/docs/Foreign.Object#t:Object) instead of [`Foreign`](https://pursuit.purescript.org/packages/purescript-foreign/5.0.0/docs/Foreign#t:Foreign)?

https://github.com/purescript-web/purescript-web-html/blob/0aa27db6d393fc53454f549566f9058147cc008a/src/Web/HTML/History.purs#L29-L29

The `purescript-foreign` repo is more for when we're reading plain JavaScript objects, and the `purescript-foreign-object` repo is more for when we're writing plain JavaScript objects. This is more like the latter situation, from the perspective of the `purescript-web-html` user API.

Like, I want to pass [`Foreign.Object.empty`](https://pursuit.purescript.org/packages/purescript-foreign-object/2.0.3/docs/Foreign.Object#v:empty) as the first argument to `pusState`, but there is no `empty` in `purescript-foreign`. So I’m going to pass `unsafeToForeign {}`.

And similarly for everywhere else in this repo.

**Comment by garyb** [comment]
I missed this issue when it was opened.

I understand where you're coming from, but think the current definition is right as it is. `pushState` doesn't accept an object for its state object, it accepts "any serializable value", which would include literals.

I dislike the fact that `Foreign` is in there at all really, but that's just because I dislike `Foreign` in general :smile: but I don't think there is a better option either - I do still prefer it over making it "any" by just having the argument as a type variable, because at least you have to think about what you're putting in there.

It sounds like adding something like an `emptyObject` to `Foreign` would be useful though!
