### ISSUE TITLE
Attribute "autocomplete" is a String -- not a Boolean 

### ISSUE THREAD

**Issue by toastal** [purescript-web/purescript-web-html#56]
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete

It can take a large number of values like `"given-name`", et. al.

**Comment by thomashoneyman** [comment]
We should probably turn this into a sum type to enumerate the possible options.

**Comment by hdgarrood** [comment]
I think strings might actually be preferable here - it probably shouldn't be a breaking change to add to the set of possibilities, especially since it seems likely that the set of possibilities might keep expanding. Also these are supposed to be low-level bindings so I think that makes using String more permissible.

**Comment by toastal** [comment]
I opened the issue with Halogen as well and I think that would be the place for a sum type or variant :)

**Comment by hdgarrood** [comment]
Actually, having looked briefly at the spec, I find the prospect of making this into a sum type somewhat terrifying, even in halogen.
